### ISSUE TITLE
Mac OS downloads page

### ISSUE THREAD

**Issue by goldfirere** [haskell-infra/hl#102]
The Mac OS downloads page needs a bit of sprucing up. I went to do this myself with a PR, but the binary there doesn't work for me! (I have 10.8. See also #32.)

A few specific clarifications that I would want:
* The second instruction says to move "it". Although just about anyone would figure out what "it" is, it would seem that the antecedent is actually the zip file, which is not what you mean.
* The third instruction doesn't quite make sense. Double-click what? Only after I downloaded and saw that unzipping gives me a .app (as opposed to a folder, which I was, for some reason, expecting) did this make sense.
* The third instruction doesn't appear to be a proper English sentence. Perhaps: "Double-click the unzipped application for instructions to install Xcode and how to add GHC to your $PATH variable." (Does the app actually give instructions about the path variable?)

Do we assume that all potential Haskell users know how to use Terminal or what a `$PATH` is? (First-years at college certainly don't meet this standard!)

**Comment by gbaz** [comment]
closed by #103?
