### ISSUE TITLE
Windows MinGHC download still link to minGHC 7.8.3 instead of 7.10.1

### ISSUE THREAD

**Issue by THeK3nger** [haskell-infra/hl#105]
Hi! I've seen that minghc 7.10.1 is [now available](https://www.fpcomplete.com/blog/2015/03/minghc-ghc-7-10) but the website still link to the old one (7.8.3).

**Comment by gbaz** [comment]
Seems to me that we should cutover all the links to the new ghc simultaneously, not just one platform at a time. Not sure of the proper timing on this.

**Comment by gbaz** [comment]
MinGHC seems to be now updated, but os x could stand to be updated, as could linux instructions...

**Comment by gbaz** [comment]
ok this was tackled, closing
