### ISSUE TITLE
Hard to get hl to build

### ISSUE THREAD

**Issue by gibiansky** [haskell-infra/hl#110]
The default build installs `pandoc==1.12.4`, which cannot build on `cabal==1.22` as documented here:

https://github.com/jgm/pandoc/issues/1526

I'm not sure how to fix this, since it *seems* that `cabal.config` specifies all the versions. (Is this using Stackage?)

What should I do? ...do I need to downgrade cabal? (That would be silly.)

**Comment by gbaz** [comment]
Have you tried altering the version in cabal.config and seeing if a newer pandoc works?

**Comment by gibiansky** [comment]
Yes, but it conflicts with something else, because all the versions are
fully specified.

**Comment by gbaz** [comment]
its just a cabal freeze file -- you can remove it and let things build unrestricted, and then force dependencies as needed.

to my knowledge, it works if you remove that file, then init a sandbox and point you cabal to stackage?

**Comment by gibiansky** [comment]
Alright, thanks.
