### ISSUE TITLE
https://www.haskell.org/visualhaskell is a 404

### ISSUE THREAD

**Issue by radix** [haskell-infra/hl#113]
There are links on the 'net to https://www.haskell.org/visualhaskell, and it seems to have disappeared.

I was looking it up because of the recent news of Microsoft releasing Visual Studio (or a subset of it) on Mac and Linux, and I assume other people will also be seeking it out for the same reason.

I don't know if this the right place to report it (it's the only vaguely relevant place I could find linked from the haskell.org front page), sorry if it isn't.

**Comment by danse** [comment]
When i query Google for `visual haskell` i do not get any result anymore pointing to that page

**Comment by mauke** [comment]
Here are some results that link to that page:

- https://ghc.haskell.org/trac/ghc/wiki/ProjectSuggestions
- http://wiki.c2.com/?HaskellLanguage
- http://www.jammni.de/php/forum.php?forum=6&posting=2421
- https://mail.haskell.org/pipermail/haskell-cafe/2007-August/029849.html

**Comment by relrod** [comment]
I'm not sure what was on that page originally. I'm happy to put in a redirect if someone who knows more about it wants to put something on the Wiki about it or similar.

Going to close this for now just to bump it out of my queue. If someone does do that, please feel free to re-open and/or @-mention me.
