### ISSUE TITLE
SHA-256 hash for Linux From Source Download

### ISSUE THREAD

**Issue by auricratio** [haskell-infra/hl#126]
I downloaded five different versions of the platform and the SHA-256 hash matches for all save the Linux From Source download. To be more specific, the download of

  https://haskell.org/platform/download/7.10.2/haskell-platform-7.10.2-a.tar.gz

does not produce a matching hash using shasum -a 256. (I even tried with -b, -p and -t options and all produce the same hash which disagrees with the published one.)

**Comment by gbaz** [comment]
closing as resolved with the new platform
