### ISSUE TITLE
Update download for Fedora.

### ISSUE THREAD

**Issue by ignoramoose** [haskell-infra/hl#127]
The syntax for the Fedora package manager has changed. Instead of using yum to install packages, now the command is "dnf". The downloads page for Fedora does not represent this change; the new command should be "sudo dnf install haskell-platform". Other than that fantastic website.

**Comment by gbaz** [comment]
Thanks! mind making a PR?

The file should be: https://github.com/haskell-infra/hl/blob/master/static/markdown/linux-install.md

**Comment by mgrabovsky** [comment]
I think OP may be talking about the [Haskell Platform page](https://www.haskell.org/platform/#linux-fedora).
