### ISSUE TITLE
Torrents for Haskell Platform, please

### ISSUE THREAD

**Issue by polkovnikov-ph** [haskell-infra/hl#128]
Currently I'm downloading Haskell Platform with speed peaking at 150 KiB/s. That's a bit unpleasant for 165 MiB executable. That's why I think we need torrents. Also torrents would drastically decrease amount of traffic and hosting costs.

**Comment by gbaz** [comment]
@mzero thoughts?

**Comment by polkovnikov-ph** [comment]
@gbaz @mzero Have you had a time to talk on this?

**Comment by gbaz** [comment]
I had a chat with some other folks who run haskell infrastructure and we think a torrent is not a great approach right now -- odds are we won' t have many seeders so there isn't going to be much in the way of performance wins. Rather we're going to focus on making sure we're using our CDN correctly to help with download speeds.
