### ISSUE TITLE
Please don't suggest unsupported operations on Arch Linux.

### ISSUE THREAD

**Issue by Earnestly** [haskell-infra/hl#134]
Under https://www.haskell.org/downloads/linux

In the Arch Linux section instead of discussing how one should update their system or suggesting `-Sy` which is [not supported](https://wiki.archlinux.org/index.php/Pacman#Partial_upgrades_are_unsupported), could it please be simply reduced to:

```
sudo pacman -S ghc cabal-install happy alex haddock
```

We get a few too many users who have been given this misinformation and wondering why certain softwares fail to start due to missing shared libraries.

**Comment by gbaz** [comment]
@Earnestly do you mind making a PR yourself? You can do it entirely within github because it is just a markdown file that needs to be edited: https://github.com/haskell-infra/hl/blob/master/static/markdown/linux-install.md

**Comment by gbaz** [comment]
Or is it just deleting "Of course you can choose" and all the subsequent text?

**Comment by Earnestly** [comment]
Yes, I took your suggestion and did a PR, thanks for the exact link.  It helped :-)

**Comment by gbaz** [comment]
accepted

**Comment by Earnestly** [comment]
Thank you

**Comment by Earnestly** [comment]
Excuse me but how long will it take for this correction to appear on the website proper?

**Comment by gbaz** [comment]
Just redeployed :-)

**Comment by Earnestly** [comment]
Thanks \o/
