### ISSUE TITLE
Installer on MacOS X el Captain

### ISSUE THREAD

**Issue by ambs** [haskell-infra/hl#141]
Hello
I know this is not website related, but not sure where to post this ticket. So, please either forward it, or close it with the reference where to post this info.

The new el Captain instlaler will fail if /usr/local is clean (empty, no folder, nothing, nada!)

Cheers

**Comment by gbaz** [comment]
@ambs was this an install on an El Capitan machine? My impression was that such machines had /usr/local folders to begin with, and certainly did so after the installation of the command line tools for Xcode...

**Comment by ambs** [comment]
Hello. /usr/local exists, but doesn't include any folder (like /usr/local/bin).
I can't debug this clearly, because in my mac it worked, but in a student with a formated machine (and /usr/local empty) the installer could not create the symlinks to the /Library/Haskell folder.

Cheers

**Comment by gbaz** [comment]
closing, as this is a platform issue and also it should be addressed with the next release...
