### ISSUE TITLE
TLS Certificate Expired for haskell.org

### ISSUE THREAD

**Issue by sinelaw** [haskell-infra/hl#144]
As Firefox puts it:

> haskell.org uses an invalid security certificate. 
> The certificate expired on 11/15/2015 08:28 AM. The current time is 11/15/2015 09:21 AM.

**Comment by relrod** [comment]
This is infra, not an hl bug. But we're on it - thanks!

**Comment by sinelaw** [comment]
Thanks! Where does one report infra bugs, btw?

**Comment by relrod** [comment]
Generally #haskell-infrastructure on freenode. There's also a tracker on https://phabricator.haskell.org/ on it, but it's mostly not used.
