### ISSUE TITLE
Windows download links of HP 7.10.3 lead to 403

### ISSUE THREAD

**Issue by bkaestner** [haskell-infra/hl#150]
Both Windows Haskell platform links on [the download page](https://www.haskell.org/platform/windows.html) ([64bit](https://downloads.haskell.org/~platform/7.10.3/HaskellPlatform-7.10.3-x86_64-setup.exe) and [32bit](https://downloads.haskell.org/~platform/7.10.3/HaskellPlatform-7.10.3-i386-setup.exe)) currently lead to a 403 HTTP error.

**Comment by gbaz** [comment]
whoops! fixed. Thanks for the report.
