### ISSUE TITLE
Reddit section in News not updating

### ISSUE THREAD

**Issue by kodaj** [haskell-infra/hl#155]
Under https://www.haskell.org/news the Reddit section in the top left corner has not been updated for a week or so. The latest item in the list is "Haskell reexport everything — a week ago", whereas https://www.reddit.com/r/haskell obviously contains much more recent items.

**Comment by chrisdone** [comment]
I think the feed changed: https://www.reddit.com/r/changelog/comments/428vdq/upcoming_reddit_change_switching_from_rss_20_to/

**Comment by gbaz** [comment]
fixed upstream now
