### ISSUE TITLE
add Releases2016.hs to https://downloads.haskell.org/~platform/8.0.1/haskell-platform-8.0.1.tar.gz

### ISSUE THREAD

**Issue by a-j-douglass** [haskell-infra/hl#163]
As of now 

https://downloads.haskell.org/~platform/8.0.1/haskell-platform-8.0.1.tar.gz (mod 25-May-2016 06:24) 

is missing 

https://github.com/haskell/haskell-platform/blob/master/hptool/src/Releases2016.hs

from haskell-platform-8.0.1/hptool/src/

I had to drop it in there manually when I was trying to make the haskell platform for centos6.

I don't know github, so if this is the wrong place for this please direct me.

**Comment by gbaz** [comment]
this is a fine place. Sorry, whoops!

**Comment by gbaz** [comment]
tarball updated, and verified to include file.
