### ISSUE TITLE
SHA-256 hash for haskell-platform-8.0.1.tar.gz correct?

### ISSUE THREAD

**Issue by schleuse2** [haskell-infra/hl#164]
Hi,

using the page
  https://www.haskell.org/platform/#linux-source
I downloaded the tarball
  https://haskell.org/platform/download/8.0.1/haskell-platform-8.0.1.tar.gz
but I got on an OpenSUSE Linux system using the tool sha256sum a SHA-256 hash 
  1b07f6cbb77ee722af2865c11ed16444663b75e6562c7cc1a9bb6dc06891a0e0
instead the on the above page mentioned (and only bad readable)
  38af99a9ae4afce56df75a753a19e7a4986bfbc8ce22f93b8308b5ab9e5a19c6
If I am the only one with that problem, what may be my error?

Jens

**Comment by gbaz** [comment]
You downloaded an old cached version of the tarball (our cdn will take some time to update).

I uploaded a newer one and changed the hash to the new one you see (starting with 3).

I just verified on the server and the new hash is correct. You can get a new tarball by appending some query params to the url to bypass the cdn.

**Comment by schleuse2** [comment]
On Fri, 27 May 2016, gbaz wrote:

> You downloaded an old cached version of the tarball (our cdn will take some time to update).
> 
> I uploaded a newer one and changed the hash to the new one you see (starting with 3).
> 
> I just verified on the server and the new hash is correct. You can get a new tarball by appending some query params to the url
> to bypass the cdn.

Doesn't help. I cleaned additionally my Firefox cache and used also 
as an alternative download tool "wget" but using for e.g.

  https://haskell.org/platform/download/8.0.1/haskell-platform-8.0.1.tar.gz?vrs=8.0.1

I got always the same tarball containing 3224024 bytes (with the SHA-256 
hash mentioned in my first report).

Ok, I will try it again tomorrow or in the next days hoping the CDN will 
have refreshed it's cache.

Thanks

Jens

P.S.: I attached a small Firefox screenshot showing the bad readability of 
the SHA-256 hash value (I used therefore the source code of the Web page).

**Comment by gbaz** [comment]
your attachment was scrubbed :-/. That said, the sha value is I think meant to be copied and pasted, not read directly from the page, fwiw.

**Comment by gbaz** [comment]
ok, I actually uploaded a new version again, and updated the hashes, and cleared the fastly cache. There may be downstream caching but I verified the sum of a downloaded file against the posted sha.

**Comment by schleuse2** [comment]
On Fri, 27 May 2016, gbaz wrote:

> ok, I actually uploaded a new version again, and updated the hashes, and cleared the fastly cache. There may be downstream
> caching but I verified the sum of a downloaded file against the posted sha.

Great, now it seems ok (haskell-platform-8.0.1.tar.gz now with
3225653 bytes).

That the attached screenshot was scrubbed I had feared. Copy and paste of 
the SHA-256 hash yesterday didn't work for me but today it works, so my 
Firefox or I have made a mistake.

Thanks

Jens
