### ISSUE TITLE
SHA-256 hash does not match website

### ISSUE THREAD

**Issue by gmlewis** [haskell-infra/hl#168]
The download here: https://www.haskell.org/platform/linux.html#linux-source
lists the SHA-256 hash as: `38af99a9ae4afce56df75a753a19e7a4986bfbc8ce22f93b8308b5ab9e5a19c6`

whereas I repeatedly get this:

```bash
$ sha256sum haskell-platform-8.0.1.tar.gz 
35f907b8ee02985eda6aa316f512c9065f6e4b9463241a033e91362c939cd1dd  haskell-platform-8.0.1.tar.gz
```

**Comment by gbaz** [comment]
Indeed -- my apologies. Now fixing the site.

**Comment by gbaz** [comment]
(the tarball had been updated to include an important additional file and the sha hadn't been updated alongside properly.)
