### ISSUE TITLE
Tutorial Fails to Accept Valid Input on Step #23

### ISSUE THREAD

**Issue by Idyllei** [haskell-infra/hl#171]
Step: https://www.haskell.org/#step23
I provided the input
```haskell
let (_, a:_) = (10,"abc") in a  -- 'a' :: Char
```
to the prompt and was not progressed to the next step. However, the valid ("spoiler") input is:
```haskell
let (_,(a:_)) = (10,"abc") in a   -- 'a' :: Char
```
Both give the same output, but only the spoiler is accepted. 
Perhaps it should be accepted at this stage even if it is not in idiomatic Haskell style.

**Comment by gbaz** [comment]
closing in favor of issue at tryhaskell site
