### ISSUE TITLE
"Lesson 2 completo!" is neither Italian, English nor Spanish

### ISSUE THREAD

**Issue by lucamolteni** [haskell-infra/hl#185]
I'm not quite sure what you wanted to write here, but this sounds awkward for both Italian and Spanish speakers, since 
"Lección" in Spanish and "Lezione" Italian are feminine, so eventually it should be 

"Lesson 2 Completa!"

Please note that also the verbe tense is also wrong, there should be a past principle, so it should be 
"Lesson 2 Completata!".

My suggestion is to keep it simple English.

**Comment by relrod** [comment]
If you still feel this is something worth changing, please file it upstream here: https://github.com/tryhaskell/tryhaskell
