### ISSUE TITLE
haskell.org/haddock is out of date

### ISSUE THREAD

**Issue by sjakobi** [haskell-infra/hl#189]
[The page](https://www.haskell.org/haddock/) only lists haddock versions up to 2.15.0 while the most recent version is [2.17.3](https://github.com/haskell/haddock/releases/tag/haddock-2.17.3-release). In particular, the [user guide](https://www.haskell.org/haddock/doc/html/index.html) is outdated and doesn't document recent features.

I guess the site should have some kind of hook that looks for fresh releases at https://github.com/haskell/haddock/releases and generates the documentation from the released tarball.

If someone can point me at the the right bit of code, I'd like to submit a patch to add such a hook.

Pinging @simonmar as he is listed in the page footer.

**Comment by simonmar** [comment]
I originally made that page, but I don't maintain Haddock any more.  I'd be delighted if someone took it over and revamped the page (or just delete it and use Hackage?)

**Comment by sjakobi** [comment]
I just saw that there's a discussion of plans for the haddock documentation at https://github.com/haskell/haddock/issues/360, I'll just chime in there.
