### ISSUE TITLE
Linux download text disappears under certain widths

### ISSUE THREAD

**Issue by tfausak** [haskell-infra/hl#195]
This text on the [Linux download page](https://www.haskell.org/platform/linux.html) for the Haskell Platform disappears when the viewport is less than 1000 pixels wide.

>  Please select your Linux distribution in the list on the right. Note that distribution-packaged versions are typically behind the current platform release. If you prefer to use the latest version rather than the distribution-packaged version, then you may use the generic Linux installer.

**Comment by gbaz** [comment]
Fixed with new platform page. Thanks for the report!
