### ISSUE TITLE
Outdated package managers

### ISSUE THREAD

**Issue by goldfirere** [haskell-infra/hl#197]
When I look at https://www.haskell.org/platform/#linux-ubuntu, I am told to use `apt` to install the platform on Ubuntu. There are two problems here:

1. I want the Minimal platform. But there's no instructions around that.

2. When I follow the instructions here, I get a platform from 2014 with GHC 7.8.3 -- not what I wanted.

At a minimum, there should be a warning that reminds users that package DBs can be out of date and that following the "generic" instructions is the only guarantee of an up-to-date install.

**Comment by gbaz** [comment]
There is such a warning, though it could be highlighted better. There's some discussion here: https://www.reddit.com/r/haskell/comments/5pc1ab/announce_haskell_platform_802/dcqx9da/?context=1

Does the proposed solution sound correct?

**Comment by goldfirere** [comment]
Yes. I see the warning now, too. It's very hard to spot. It should be right near the Good News part. Even better would be to divide up the icons on the right hand side between a "Get the latest:" with generic and source icons and "Use package manager:" with the others.

You're right that package managers are often a bit behind. But when I'm referred to the package manager specifically by the package's website, I interpret that to mean that the package manager is up to date.

Thanks!

**Comment by gbaz** [comment]
ok, now there's more warnings in the place you suggest and it no longer says if the news is "good" or not :-)
