### ISSUE TITLE
Generic Linux HP "Core" is not Core!

### ISSUE THREAD

**Issue by goldfirere** [haskell-infra/hl#198]
When I download https://haskell.org/platform/download/8.0.2/haskell-platform-8.0.2-unknown-posix--minimal-x86_64.tar.gz and install, I get all the HP libraries, not just the Core ones.

**Comment by gbaz** [comment]
eep! cc @dagit

On Tue, Jan 24, 2017 at 9:34 PM, Richard Eisenberg <notifications@github.com

**Comment by dagit** [comment]
I'm not sure what happened to cause this, but I did build the full version
first and then the minimal version. So I probably hit a bug in our
packaging tool.

Sorry for any inconvenience this has caused.

**Comment by gbaz** [comment]
new builds and hashes now in place for affected packages
