### ISSUE TITLE
Wrong version in path

### ISSUE THREAD

**Issue by rzrbny** [haskell-infra/hl#199]
When downloading the windows distribution form this link https://www.haskell.org/platform/ the paths specified at the bottom of the page are for the wrong version of Haskell Platform, 8.0.1 instead of 8.0.2

extra-prog-path: C:\Program Files\Haskell Platform\**8.0.1**\msys\usr\bin
extra-lib-dirs: C:\Program Files\Haskell Platform\**8.0.1**\mingw\lib
extra-include-dirs: C:\Program Files\Haskell Platform\**8.0.1**\mingw\include

**Comment by gbaz** [comment]
thanks! we'll fix soon...

**Comment by gbaz** [comment]
fixed
