### ISSUE TITLE
Support shallow git clone

### ISSUE THREAD

**Issue by snowleopard** [haskell-infra/hl#202]
Shallow git cloning from `git://git.haskell.org/ghc.git` doesn't work at the moment:
```
$ git clone --depth 1 --recursive git://git.haskell.org/ghc.git --quiet
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

We'd like to have a shallow clone of GHC to speed up the CI scripts, as discussed in these PRs:

* https://github.com/snowleopard/hadrian/pull/298
* https://github.com/snowleopard/hadrian/pull/300 

Presumably, this can be fixed simply by updating to a newer `git` version.

**Comment by gbaz** [comment]
This is the wrong tracker for such a thing. This is for the haskell.org website. Changes to GHC's repo are best filed at the ghc trac: https://ghc.haskell.org/trac/ghc

**Comment by snowleopard** [comment]
@gbaz Thanks, will resubmit this to the GHC Trac.
