### ISSUE TITLE
One of the examples in Try it! doesn't work

### ISSUE THREAD

**Issue by rakyi** [haskell-infra/hl#203]
```haskell
λ do line <- getLine; putStrLn line
> hi
mueval-core: Time limit exceeded
ExitFailure 1
```

Also happens on https://tryhaskell.org/

**Comment by unhammer** [comment]
Also, this is weird:

![haskell-ru2](https://cloud.githubusercontent.com/assets/56868/23898858/1365bc58-08b3-11e7-8462-858dd2067b6e.png)

**Comment by gbaz** [comment]
Closing in favor of the tryhaskell ticket.
