### ISSUE TITLE
Spam in the haskell-cafe feed

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hl#204]
On the news page https://www.haskell.org/news there is a feed that displays what is supposed to be the haskell-cafe mailing list. However, since it takes its info from the Google Groups, its full of spam.

Someone either needs to properly administer the Google Group or get the feed data directly from the haskell-cafe mailing list.

See : https://www.reddit.com/r/haskell/comments/5x9meo/haskellcafe_appears_to_be_suffering_from_spam/deggjiv/

**Comment by gbaz** [comment]
That all comes via https://github.com/haskellnews/haskellnews which is where a ticket should be filed.

That said, I've unsuccessfully tried to reach out to whomever admins the google group in the past on a few issues and gotten no response.
