### ISSUE TITLE
Timeouts and strange results in Try it! REPL

### ISSUE THREAD

**Issue by ccressent** [haskell-infra/hl#207]
Playing with the "Try it!" REPL on https://www.haskell.org/:

```
λ putStrLn "Hello"
mueval-core: Time limit exceeded
ExitFailure 1
```

```
λ print 5
p
λ print 5
mueval-core: Time limit exceeded
ExitFailure 1
```

```
λ print (Just 5)
p
λ print (Just 5)
ru
λ print (Just 5)
Just 5
```

From my (limited) testing, it seems to only happen with expressions involving `IO`.
After an expression is successfully evaluated it just starts working without timeouts, as if the result had been cached.

**Comment by mjhoy** [comment]
I get this for simple math expressions too, e.g.

```
λ 23 * 70
mueval-core: Time limit exceeded
ExitFailure 1
```

**Comment by gbaz** [comment]
cf: https://github.com/tryhaskell/tryhaskell/issues/46 and https://github.com/tryhaskell/tryhaskell/issues/45

**Comment by gbaz** [comment]
ok should be closed as per those tickets
