### ISSUE TITLE
Videos not available 

### ISSUE THREAD

**Issue by p-alik** [haskell-infra/hl#213]
Not sure if it's known, but it looks like all the video resources defined in [vids](https://github.com/haskell-infra/hl/blob/master/src/HL/Model/Videos.hs#L21) are not available anymore.

**Comment by gbaz** [comment]
Eep! thanks for the catch. We should probably update them anyway, but as a
quick measure I'm reaching out to see if they can be restored.

**Comment by gbaz** [comment]
restored now.

**Comment by p-alik** [comment]
Thanks for restoring.
