### ISSUE TITLE
redirects for old urls?

### ISSUE THREAD

**Issue by mjhoy** [haskell-infra/hl#217]
I am reading A History Of Haskell: Being Lazy With Class. There are several instances of URLs that point to 404s, all on haskell.org, that perhaps could be redirects.

- haskell.org/humor (should be: https://wiki.haskell.org/Humor)
- https://www.haskell.org/hat -> https://wiki.haskell.org/Hat
- http://haskell.org/development/views.html -> ???

**Comment by gbaz** [comment]
we can redirect views to the archive.org page: http://web.archive.org/web/20040107202217/http://haskell.org/development/views.html

@relrod can you add these redirects to the nix config?

**Comment by relrod** [comment]
@gbaz I feel weird about linking to an archive.org page. If that info is still relevant and useful, could we make a wiki page with it instead and point to that?

**Comment by gbaz** [comment]
It isn’t relevant in any current sense. It is of historic importance, and
cited in some papers, etc. So it is if use to people researching past
publications and research, and doesn’t appear to be published elsewhere...

**Comment by relrod** [comment]
I get that it's of historic importance. Just wondering if it would be worth making it into a wiki page with the same info (verbatim, save for changes needed to convert to wiki-markup) and linking to that instead. I guess the archive page is fine, it just makes me feel a bit weird.

**Comment by relrod** [comment]
In any case, I'll try to get these added soon.

**Comment by mjhoy** [comment]
Closing to reopen on the new repo: https://github.com/haskell-infra/www.haskell.org/issues/261
