### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by azurinko** [haskell-infra/hl#219]
Guys, you don't have a contact page listed. I wanted to write you something.

**Comment by gbaz** [comment]
general discussion on the site can occur on the haskell-community@h.org list https://mail.haskell.org/cgi-bin/mailman/listinfo/haskell-community

**Comment by thoughtpolice** [comment]
This seems orthogonal to the real complaint which is that the user has no idea *where* to write something, I assume?

Perhaps we should file a new bug about adding a "About this website" or "Contact the admins" link somewhere. It's not unreasonable that people would look there for it.

**Comment by gbaz** [comment]
But the user did find a place to write something -- right here! The bottom footer explicitly says this is for comments as well.
