### ISSUE TITLE
Your mail is not working.

### ISSUE THREAD

**Issue by azurinko** [haskell-infra/hl#220]
####################################################################
# THIS IS A WARNING ONLY.  YOU DO NOT NEED TO RESEND YOUR MESSAGE. #
####################################################################

Your message could not be delivered for more than 12 hour(s).
It will be retried until it is 2 day(s) old.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<haskell-community@h.org>: connect to h.org[50.63.46.1]:25: Connection timed
    out

**Comment by gbaz** [comment]
yes i didn't literally mean h.org i mean the mailing list at haskell.org, as i linked to in the prior ticket.
