### ISSUE TITLE
Incorrect "Download GHC now" redirect

### ISSUE THREAD

**Issue by x1ddos** [haskell-infra/hl#231]
The https://www.haskell.org/downloads/linux page links to https://www.haskell.org/ghc/download with text "Download GHC now" in the "Manual install" section, which redirects back to https://www.haskell.org/downloads.

I believe this is incorrect and the link should point/redirect to something like https://www.haskell.org/ghc/ instead.

**Comment by gbaz** [comment]
resolved, thx for the report.
