### ISSUE TITLE
cabal download instruction error: 'cabal' should be 'Cabal'

### ISSUE THREAD

**Issue by instinctive** [haskell-infra/hl#242]
I've looked through this repo and can't find the cabal pages to fix it myself.
Page: https://www.haskell.org/cabal/download.html:

    If you want to upgrade to the latest stable version, just run:
    $ cabal install cabal cabal-install

In the command, `cabal` should be `Cabal` (capitalized).

**Comment by gbaz** [comment]
fixed, thanks! (the cabal website is managed separately from the repo).
