### ISSUE TITLE
https://www.haskell.org/news: Internal Server Error as of 12:23 pm GMT, Nov 9, 2018

### ISSUE THREAD

**Issue by kodaj** [haskell-infra/hl#244]
![image](https://user-images.githubusercontent.com/4332563/48262415-5750dd00-e41a-11e8-9b32-12e527be6890.png)

**Comment by kodaj** [comment]
Since it's not looking like the haskellnews problem is going to be fixed any time soon, wouldn't it be better to temporarily remove the News link from the haskell.org front page?

**Comment by jchevali** [comment]
Yes, it would.  Otherwise it can lead the undiscerning visitor to think that Haskell - the language, not the news - is no longer getting updates, in other words it's dead.  I'd expect Haskell.org to receive many first-time visitors and that creates a bad impression.

**Comment by gbaz** [comment]
for now we've got it entirely disabled until someone wants to write/run a new news aggregator service.
