### ISSUE TITLE
Deprecate GHC for OS X page

### ISSUE THREAD

**Issue by fghibellini** [haskell-infra/hl#247]
I accidentally installed ghc 7.8.4 (released December 23rd 2014)  following https://www.haskell.org/downloads/osx .
There was an open issue that never got resolved https://github.com/ghcformacosx/ghc-dot-app/issues/51 .
I guess the whole page can just be removed at this point since there is https://www.haskell.org/platform/mac.html and on IRC I just got advised to install ghc directly from https://www.haskell.org/ghc/download_ghc_8_6_3.html#macosx_x86_64 .

**Comment by gbaz** [comment]
Good point! Nothing else on the site links to that page afaik, so I wonder how you got to it? But that said, its probably safer to remove it entirely.

**Comment by fghibellini** [comment]
<img width="767" alt="screen shot 2018-12-14 at 14 17 24" src="https://user-images.githubusercontent.com/4848178/50005600-334d6200-ffab-11e8-9e38-8940a1b11f3a.png">

I just wanted ghc and so I didn't choose the first option (which includes stack and other stuff I didn't need).

**Comment by gbaz** [comment]
That page is now gone with the site revamp.

And google has noticed and it no longer appears in results either :-)
