### ISSUE TITLE
Create haskell.org/ghcup/

### ISSUE THREAD

**Issue by m-renaud** [haskell-infra/hl#248]
[ghcup](https://github.com/haskell/ghcup) is becoming the preferred way to install the Haskell tool chain, it should have a place on the official Haskell website; it could start as a simple HTML+CSS+JS webpage.

It would be great if it looked something like the [rustup](https://rustup.rs/) page which has: one sentence describing what it is, a command to run to install the whole toolchain (auto-detected based on OS), where to ask for help, and an "official Rust project" badge.

Once the [bootstrap-haskell script is merged](https://github.com/haskell/ghcup/pull/40) this script should also be hosted on haskell.org to make it clear that it's an official offering. Then installing the Haskell toolchain would be as easy as:

    curl https://get-ghcup.haskell.org -sSf | sh

/cc @hasufell

**Comment by gbaz** [comment]
If this is just about a subdomain in the haskell infra, it doesn't belong on this repo, which is about the webpage as such. Just reach out to admin@h.org when things are ready to go.

**Comment by hasufell** [comment]
You mean people click on haskell-platform, then are told "use ghcup", click on ghcup page, and then download?

**Comment by gbaz** [comment]
Of course not! That would be silly! Rather, what I'd like to happen is that A)  the platform page can give direct install instructions for ghcup (the script would help with this) and furthermore once we have the new platform plans as sketched above, we could even possibly just swap the download page for the platform install page entirely, and it might no longer be controversial to unify in that way.

**Comment by m-renaud** [comment]
> a subdomain in the haskell infra...reach out to admin@h.org 

Will do, wasn't sure what the distinction was for what things belonged here vs. in a separate subdir/repo. As @hasufell mentioned this wasn't _just_ about a subdomain but also updating /downloads. This also ties into #221 which I think is a great improvement over what's there now, and could be augmented to include ghcup once it is GA.

> we could even possibly just swap the download page for the platform install page entirely

I'd be in favour of that as well, it appears that page already has OS auto-detect which is really nice. Do you know what the release cadence is for Haskell PLatform and when it might be possible to recommend ghcup for Mac?

**Comment by hasufell** [comment]
bootstrap haskell script was merged https://github.com/haskell/ghcup/commit/225d2d2be41ac38365de074e1d812f02d16fc965

**Comment by gbaz** [comment]
did we want to add a subdomain still? how/where should it point? or should we host the script directly as well?

**Comment by m-renaud** [comment]
My vote would be:

https://haskell.org/ghcup - super simple landing page with what ghcup is and command to get it (a la https://rustup.rs/)

https://get-ghcup.haskell.org - where the script is hosted on the haskell.org domain, indicating its an officially supported project

**Comment by hasufell** [comment]
Someone just gotta do it. The details are not that important. I don't have access to any infrastructure.

**Comment by gbaz** [comment]
just to close the loop, I set up the account and contacted hasufell with the login info.
