### ISSUE TITLE
Outline visible on clicking tabs

### ISSUE THREAD

**Issue by psibi** [haskell-infra/hl#25]
Browser: Firefox 32 on Linux

Whenever I click on any of the tabs (Downloads, Community, Documentation or News), there is an rectangular outline visible for some fraction of a second on those `<a></a>` links. I find that as annoying but I agree it is more of a personal taste. If there is an interest in removing that outline, I can send a patch for that.

**Comment by danse** [comment]
Hum this was probably referring to some old version of the site, i cannot reproduce it anymore

**Comment by psibi** [comment]
@danse I'm able to reproduce it in firefox. Although I'm little nervous after seeing the comment of @relrod :)

**Comment by danse** [comment]
Right, i can reproduce in Firefox as well ... what do you mean you are nervous? Do you still think that it is a good idea to remove it?
