### ISSUE TITLE
Haskell art link on comunity page is outdated

### ISSUE THREAD

**Issue by praduca** [haskell-infra/hl#252]
The link to the Haskell art group on the community page of `haskell.org` page points to an archived version of the list. Apparently (better confirm with some actual member :) the list changed to [here](https://we.lurk.org/hyperkitty/list/haskell-art@we.lurk.org/) 

The new address is on a subdomain of the same domain, and the old one is working, just inform that the list is archived (very confusing indeed :)

**Comment by gbaz** [comment]
fixed in the new repo.
