### ISSUE TITLE
Mac OS X instructions don't work for enough versions of OS X

### ISSUE THREAD

**Issue by bitemyapp** [haskell-infra/hl#32]
etrepum has a point about the OS upgrades being free, but we still need to do something for people that can't or won't upgrade for various reasons.

I think binary distribution as I suggest in my guide would be best.

https://github.com/bitemyapp/learnhaskell#mac-os-x

With a little sprucing up, this could be a good guide for getting the bindist setup on Mac OS X:

http://www.davesquared.net/2014/05/platformless-haskell.html

**Comment by goldfirere** [comment]
Yes, please. I run 10.8 on both my Macs, after a terrible experience with 10.9 being so slow that I was unable to function efficiently. (I reformatted and reinstalled 10.8.) I was quite surprised that the main downloads mechanism on the site doesn't work for me.
