### ISSUE TITLE
Is the "open-source community effort" with videos really useful on the front page ?

### ISSUE THREAD

**Issue by rvion** [haskell-infra/hl#37]
I think it is not, because:
- it is not usefull for newcomers.
- it is not logically organised
- it doesn't say much concretely
- it takes lots of space
- it makes the home page change colors too much (white/ dark / white / dark/white) (hard on eyes)
- it should better be part of community page
- it gives the impression haskell is not made for business but for scholar

What do you think ?

**Comment by darthdeus** [comment]
Interesting how people have many different opinions on this (in the reddit discussion as well). I always wished the main Haskell site had more mentions about Haskell-related videos.

Imho one big value they provide is the _people are actually using this in the real world, not just talking about it on the internets_ kind of argument.

**Comment by gbaz** [comment]
i think the redesign solved most everything except for the fact of videos, which people seem fine with for the most part, so...
