### ISSUE TITLE
Lambda char doesn't render in nav header on front page

### ISSUE THREAD

**Issue by johntyree** [haskell-infra/hl#44]
![2015-01-26_11 01 31 73](https://cloud.githubusercontent.com/assets/108972/5903987/aab661ee-a54a-11e4-830c-d0c92e4a150e.png)

Is there a web-font or something that isn't being loaded?

**Comment by chrisdone** [comment]
Hm, that should be fixed. What's your browser?

**Comment by johntyree** [comment]
I get the same in both Firefox 35 and Chromium 39

**Comment by chrisdone** [comment]
I'll fix this before it goes life. Can you see anything, any errors in the chromium output or so? Anything about lacking web fonts?

**Comment by johntyree** [comment]
Yep, sorry. Should have included these earlier.
Chromium console:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://haskell-lang.org/static/css/fonts/haskell.ttf Failed to load resource: the server responded with a status of 404 (Not Found)
````

**Comment by johntyree** [comment]
Firefox:

```
downloadable font: download failed (font-family: "haskell" style:normal weight:normal stretch:normal src index:1): status=2147746065
source: http://haskell-lang.org/static/css/fonts/haskell.woff haskell.font.css:1
downloadable font: download failed (font-family: "haskell" style:normal weight:normal stretch:normal src index:2): status=2147746065
source: http://haskell-lang.org/static/css/fonts/haskell.ttf
```

**Comment by chrisdone** [comment]
Ohh. That's the old domain. I'm going to make it redirect. The canonical location is http://new-www.haskell.org/

**Comment by johntyree** [comment]
![2015-01-28_12 13 18 85](https://cloud.githubusercontent.com/assets/108972/5943705/e515c4f4-a6e6-11e4-910f-b2677fb67be9.png)

No errors this time. Just doesn't render correctly.

**Comment by gbaz** [comment]
Still not working, just a box for me. A penguin for others. Webfont support is inconsistent. We should kill this or replace it with a picture :-(

**Comment by chrisdone** [comment]
Ah, it's a simple error in the CSS. Confirm fixed on this test domain? haskell-lang.org

**Comment by Heather** [comment]
experienced the same https://twitter.com/Cynede/status/566114355163705345
now on http://haskell-lang.org it seems like fixed

**Comment by chrisdone** [comment]
@johntyree Confirm on haskell-lang?

**Comment by johntyree** [comment]
:+1: looks good.

@gbaz I wish I had had a penguin :penguin: ...
