### ISSUE TITLE
Interactive interpreter on Chrome on Android

### ISSUE THREAD

**Issue by DaveCTurner** [haskell-infra/hl#50]
... doesn't seem to accept character key presses. Enter works but letters and numbers seem not to?

**Comment by chrisdone** [comment]
I'll try this on my samsung later.

**Comment by gelisam** [comment]
I can reproduce this too. Perhaps it's related to the android keyboard's word suggestions? Numbers and symbols don't trigger any such suggestion, so that would be one possible difference between the two types of characters.

**Comment by gelisam** [comment]
If the word suggestions indeed turn out to be the problem, I've noticed that the feature is turned off for the textboxes of google translate, so maybe there's some html attribute which turns it off.

**Comment by gelisam** [comment]
I got a fix for it, I'll sent a pull request.
