### ISSUE TITLE
type error: "install Haskell"

### ISSUE THREAD

**Issue by jwaldmann** [haskell-infra/hl#56]
This page https://www.haskell.org/downloads/linux often uses wording "install Haskell". I think that's a type error. Haskell is a language. You cannot install a language. (Example: you cannot "install C"). You can install a compiler, a set of libraries, etc.

**Comment by chrisdone** [comment]
It only uses it under the Arch Linux section which was contributed yesterday. Haskell's a language, we get it. ;-)
