### ISSUE TITLE
HaskellWiki update?

### ISSUE THREAD

**Issue by takenobu-hs** [haskell-infra/hl#60]
Hi, 
Thank you for a cool site!

Do you stopped News[1] HaskellWiki updates?

[1] https://www.haskell.org/news

**Comment by chrisdone** [comment]
The URL must've changed or something. This is a [haskellnews](https://github.com/chrisdone/haskellnews) issue. I'll check it out.

**Comment by chrisdone** [comment]
Moved to https://github.com/chrisdone/haskellnews/issues/11.

**Comment by takenobu-hs** [comment]
Ongoing correspondence Thank you very much.

Excellent web for community  :+1:
