### ISSUE TITLE
news/haskell-cafe should link to pipermail

### ISSUE THREAD

**Issue by jwaldmann** [haskell-infra/hl#63]
supporting the remark by Henning Thielemann https://mail.haskell.org/pipermail/haskell-cafe/2015-February/118181.html

> I would prefer if the links in the Haskell News go to 
> haskell.org/pipermail (or mail.haskell.org) and not to googlegroups. 

(not just for the javascript reason)  the various haskell mailing lists are just that: mailing lists, and have no relation to google (I hope). We probably allow/want google to index them, but why should we send haskell-cafe readers (coming from this News page) to their servers?

**Comment by chrisdone** [comment]
Google was the only RSS feed I could find for haskell-cafe.

**Comment by jwaldmann** [comment]
I see. Can pipermail not do this? (cf. http://sourceforge.net/p/mailman/patches/192/ )

Else, either compute the pipermail locations from google's feed (but of course it's their business plan to make that hard), or parse the real (pipermail/by date) archive page. (I may look into it.)

I guess the relevant source code loaction is https://github.com/chrisdone/haskellnews/blob/master/src/HN/Model/Feeds.hs so this is really a feature request for `haskellnews`. (Does `haskellnews` provide a feed?)

**Comment by chrisdone** [comment]
> I see. Can pipermail not do this? (cf. http://sourceforge.net/p/mailman/patches/192/ ) Else, either compute the pipermail locations from google's feed (but of course it's their business plan to make that hard), or parse the real (pipermail/by date) archive page. (I may look into it.)

No idea. That's too much work for me personally to bother with (google's fine for me), but I'd merge any patches changing how it pulls in the feed.

> I guess the relevant source code loaction is https://github.com/chrisdone/haskellnews/blob/master/src/HN/Model/Feeds.hs so this is really a feature request for haskellnews

Yeah, let's move this to haskellnews's issue tracker.

> Does haskellnews provide a feed?

For simplicity HN provides a stripped down page that HL embeds to reproduce the same "grouped" page.

**Comment by chrisdone** [comment]
Moved to https://github.com/chrisdone/haskellnews/issues/12
