### ISSUE TITLE
Linux install instructions should be one step

### ISSUE THREAD

**Issue by chrisdotcode** [haskell-infra/hl#74]
``` bash
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:hvr/ghc
sudo apt-get update
sudo apt-get install -y cabal-install-1.20 ghc-7.8.4
cat >> ~/.bashrc <<EOF
export PATH=~/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.8.4/bin:$PATH
EOF
export PATH=~/.cabal/bin:/opt/cabal/1.20/bin:/opt/ghc/7.8.4/bin:$PATH
cabal update
cabal install alex happy
```

is pretty scary and should be a one-step install, preferably one of those `curl haskell.org/linux-install.sh | sh` things (or `curl haskell.org/linux-install.sh > /tmp; chmod +x /tmp/linux-install.sh; sudo /tmp/linux-install.sh` if you're like me and don't like 'pipe directly from the internet scripts').

Additionally, cabal download should probably be a direct link to the archive, considering a beginner wouldn’t be able to find the tgz, since it's all the at the bottom of the page.

Actually, cabal setup could probably all be included in the 'one-click install' script, too. Or we can just link to the downloads page of the platform directly.

I'm willing to contribute this all if approved.

**Comment by chrisdone** [comment]
They are indeed long instructions. A script to do them above (but not excluding!) these full instructions would be okay from my side.

**Comment by gbaz** [comment]
Platform link in #83
