### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by wdanilo** [haskell-infra/hl#75]
Hello! When we are going over the tutorial, one of the sentences we see is:
```
Tuples, because sometimes one value ain't enough!
Watch out for aaadfss! You should keep their credentials for the police.

My nemesis is 28 years of age: (28,"chirs")
```

And of course the part ```My nemesis is 28 years of age: (28,"chirs")``` is wrong.

**Comment by chrisdone** [comment]
It says "my nemesis". What's the problem?

**Comment by chrisdone** [comment]
You think it should be changed to be in second-person?

**Comment by wdanilo** [comment]
Ouch, I didn't know such word as `nemesis` exist in english vocabulary, sorry for the confusion - my first impression was, that the sentence is just improper english one.

**Comment by chrisdone** [comment]
Okay dokay. Any changes necessary here then?

**Comment by wdanilo** [comment]
I dont think so, its ok :)
