### ISSUE TITLE
Documentation Cleanup

### ISSUE THREAD

**Issue by gbaz** [haskell-infra/hl#76]
Should link Hoogle, Hayoo, Wiki.
Also one good library reference for stdlibs -- probably platform module docs or at least base docs?

Should eliminate new/old book division, and ensure all books are linking latest versions.
Should probably link more course materials/videos directly.

**Comment by darthdeus** [comment]
Why do you think that the separation of old/new books is bad? Having read (or at least skimmed through both [Programming in Haskell](http://www.cs.nott.ac.uk/~gmh/book.html) and [Haskell - The Craft of Functional Programming](http://www.cs.kent.ac.uk/people/staff/sjt/craft2e/) I have to say that they both felt a little dated, at least compared to LYAH and RWH. That's not to say that they are bad books, but I probably wouldn't recommend them to a beginner.

Maybe removing the separation but adding a _release date_ or something of that sort would be the best solution?

**Comment by gbaz** [comment]
Well as a comment explained on reddit, the old/new isn't really true because of new editions of books :-)

"What I was irritated by was the "blessed" top section which included Real World Haskell (2007) and Learn You A Haskell (2011) and the not blessed "older" section which included Hutton's book (2007) and Simon Thompson's (2011)."

That post suggested Hudak's classic HSoE, which is indeed old. The Haskell School of Music, by Hudak, though not final, is much more recent and perhaps we could also link that:

http://haskell.cs.yale.edu/?post_type=publication&p=112

**Comment by gbaz** [comment]
now in pull request #83
