### ISSUE TITLE
Downloads section

### ISSUE THREAD

**Issue by cies** [haskell-infra/hl#93]
Here's some ideas I have for the "Downloads" section. I think the "Downloads" link in the navbar can be more calling and more descriptive if renamed to "Get it".

First the text as I think would be nice to have on that page:

---------------

# Get Haskell

Haskell programming language
[[specification|https://wiki.haskell.org/Language_and_library_specification]].
In order to run code written in Haskell you need a compiler,
the [[Glasgow Haskell Compiler|wikipedia]] (GHC) is the most common choice.
But be informed that [[other Haskell compilers]] exists.

### Haskell from your browser

If you rather not want to install something on your computer
there are several options:

* [[Try Haskell]], an open source Haskell-from-your-browser,
  which includes a little tutorial.
* FPComplete's [[Haskell Center]], a very feature rich Haskell
  IDE for the browser (free community licenses are available).

### Install GHC and tools on your computer

Depending on your operating system you can install Haskell in
different ways. We *recommend* you to install the latest version
of the Glasgow Haskell Compiler, either from a software
repository, using an installer or from source.

Alternatively you may also install the [[Haskell Platfrom]]
software bundle or (in case you make use of a free software
operating system) install the GHC version provided by your
distribution.

Please choose your operating system type for further instructions:

* Linux
* OSX
* Windows
* Other

### Haskell libraries

After you have installed Haskell on your computer, you will
probably want to explore the [[wealth of quality libraries]]
that the Haskell community maintains.

--------------

The Haskell Platform link to point directly to the HP site, or have a local page describing it use case and why many go without it these days.

A specific page need then be made for libraries, for which I propose the following structure:

* Get Haskell libraries
   * Cabal
   * Package repositories
      * Hackage
      * Stackage

-----------------

Once again, just an idea. Looking for feedback...

**Comment by gbaz** [comment]
As per #55 we want _less_ biased presentation of bare install vs. platform, not more.

This is a downloads page so I don't think it should link to "in-browser" solutions. I do agree that we should have links to a wiki page that should be created listing other compilers and in-browser things too (as well as e.g. purescript, ghcjs, soforth).

I don't see why we want a link to the specs of the language here, as we have them on the documentation page.

On the libraries issue I could go both ways pulling that to a separate page or leaving it below -- curious about your motivations and how you would see a separate libs page.

**Comment by cies** [comment]
> As per #55 we want less biased presentation of bare install vs. platform, not more.

Ok. (I recommend people to Haskell sometimes, and I see HP hurts them a lot, as they all want to do webdev)

> This is a downloads page so I don't think it should link to "in-browser" solutions. I do agree that we should have links to a wiki page that should be created listing other compilers and in-browser things too (as well as e.g. purescript, ghcjs, soforth).

I was thinking that --if this section is mainly for new folks-- why not show them the easy route here as well. W.r.t. "this is a Downloads page", I suggested it to be renamed to "Get it" (more call-to-action, more closely covering content).

> I don't see why we want a link to the specs of the language here, as we have them on the documentation page.

I do this to show that GHC is "one of the compilers", and many compilers may implement Haskell.

> On the libraries issue I could go both ways pulling that to a separate page or leaving it below -- curious about your motivations and how you would see a separate libs page.

Because it is 2nd to getting GHC+tools installed. The libs page can be referred to from all OS-specific install guides. Less distraction at first, more able to go in-depth. I outline what I think is a suitable structure (the nested un-ordered lists) for the libs-page.

**Comment by goldfirere** [comment]
Silence can be seen as acquiescence, so I'll speak up: I generally disagree with the changes suggested here. I vastly prefer "Downloads" to "Get it" -- whenever I want to start using a tool, I look for "Downloads" first.

@cies, what about the HP throws people off? Perhaps it doesn't have all the libraries your new users need, but then neither would the bare compiler. How does HP hurt?

On the other hand, as someone who quickly clicks "Downloads" at sites, I think having a mention of/link to web access to Haskell isn't a bad idea.

**Comment by bitemyapp** [comment]
@goldfirere Haskell Platform fixes package versions globally that don't need to be and creates confusing problems that new users do not understand and cannot resolve themselves. The first step when a new user can't get something to build often ends up being an embarrassing, "Sorry, you can't use Haskell Platform with something that new, please uninstall it and get a vanilla GHC/Cabal setup going".

**Comment by cies** [comment]
@goldfirere, as @bitemyapp explains very well there are some big issues with HP that will most likely never be resolved.

Especially now that [Stack](https://github.com/commercialhaskell/stack) is out and picking up momentum, I personally consider HP completely superseded.

**Comment by gbaz** [comment]
this discussion has been overtaken by many subsequent ones, closing.
